### PR TITLE
Update _index.md

### PR DESCRIPTION
**Pull request by SilSever**

### CODE REVIEW

**Comment by crisostomi** [comment]
### <span aria-hidden="true">👷</span> Deploy Preview for *gladia* processing.


|  Name | Link |
|---------------------------------|------------------------|
|<span aria-hidden="true">🔨</span> Latest commit | 0fe896981b394194ca5db7047cc99662c4fb6149 |
|<span aria-hidden="true">🔍</span> Latest deploy log | https://app.netlify.com/sites/gladia/deploys/63e2777c327df80008044c81 |

**Review by teelinsan — CHANGES_REQUESTED** [review]
Add icons

**Comment by teelinsan** [comment]
@SilSever hai fixato le icone? Si può mergiare?

**Comment by crisostomi** [comment]
> @SilSever hai fixato le icone? Si può mergiare?

bump, what's going on here

**Review by crisostomi — APPROVED** [review]

**Review by teelinsan — APPROVED** [review]

**Pull request merged**
